title: Rapport d'analyse du travail
description: >
  Analyse du travail et développement des compétences à la RATP
baseurl: "/at-ratp"
url: "stephmnt.github.io"
paginate:	2 # The number of posts to show per page on your homepage
name: "Stéphane Manet"
markdown: kramdown
permalink: none
kramdown:
  parse_block_html: true
gems:
  - jekyll-paginate
